package net.appitiza.moderno.constants

class Constants {
    companion object {
        const val PREF_KEY_IS_USER_LOGGED_IN = "isUserLoggedIn"
        const val PREF_KEY_IS_USER_DISPLAY_NAME  = "displayname"
        const val PREF_KEY_IS_USER_EMAIL = "useremail"
        const val PREF_KEY_IS_USER_PASSWORD = "userpassword"
        const val PREF_KEY_IS_USER_USER_TYPE = "usertype"
        const val PREF_KEY_IS_USER_USER_IMEI = "userimei"
        const val PREF_KEY_IS_USER_USER_SALARY = "salary"
        const val KEY_REQUESTING_LOCATION_UPDATES = "requesting_locaction_updates"
        const val PREF_NAME = "prefModerno"
        const val COLLECTION_USER = "users"
        const val COLLECTION_SITE = "sites"
        const val COLLECTION_CHECKIN_DATA = "checkin"
        const val COLLECTION_CHECKIN_HISTORY = "checkin_history"
        const val COLLECTION_INCOME_EXPENSE = "expense_income_details"
        const val COLLECTION_EXPENCE_CATEGORY = "expense_category"
        const val COLLECTION_INCOME_CATEGORY = "income_category"
        const val DOCUMENT_USER = "users"
        const val CHECKIN_USER = "users_email"
        const val CHECKIN_NAME = "users_name"
        const val SITE_DOCUMENT_NAME = "sites"
        const val USER_EMAIL = "email"
        const val USER_DISPLAY_NAME = "display_name"
        const val USER_TOKEN = "token"
        const val USER_PASSWORD = "password"
        const val USER_IMEI = "imei"
        const val USER_SALARY = "salary"
        const val USER_TYPE = "type"
        const val USER_REG_TIME = "time"
        const val SITE_NAME = "site_name"
        const val SITE_TYPE = "site_type"
        const val SITE_DATE = "site_date"
        const val SITE_COST = "site_cost"
        const val SITE_CONTACT = "site_contact"
        const val SITE_PERSON = "site_person"
        const val SITE_LAT = "lat"
        const val SITE_LON = "lon"
        const val SITE_LOCATION = "location"
        const val SITE_STATUS = "site_status"
        const val CHECKIN_SITE = "site"
        const val CHECKIN_SITENAME = "site_name"
        const val CHECKIN_USEREMAIL = "email"
        const val CHECKIN_USERNAME = "name"
        const val CHECKIN_CHECKIN = "checkin"
        const val CHECKIN_CHECKOUT = "checkout"
        const val CHECKIN_PAYMENT = "payment"
        const val CHECKIN_PAYMENT_TYPE = "payment_type"
        const val COLLECTION_NOTIFICATION = "notification"
        const val NOTIFICATION_ID = "id"
        const val NOTIFICATION_TITLE = "title"
        const val NOTIFICATION_MESSAGE = "mesage"
        const val NOTIFICATION_TO = "to"
        const val NOTIFICATION_TIME = "time"

        const val COLLECTION_DEVICE_CHANGE_REQUEST = "change_device_request"
        const val DEVICE_CHANGE_REQUEST_IMEI = "imei"
        const val DEVICE_CHANGE_REQUEST_CURRENT_IMEI = "current_imei"
        const val DEVICE_CHANGE_REQUEST_REASON = "reason"
        const val DEVICE_CHANGE_REQUEST_EMAIL = "email"
        const val DEVICE_CHANGE_REQUEST_NAME = "name"
        const val DEVICE_CHANGE_REQUEST_STATUS = "status"
        const val DEVICE_CHANGE_REQUEST_TIME = "time"

        const val ADMIN_PAYMENT = "admin_pay"
        const val CLIENT_PAYMENT = "client_pay"

        const val EXPENSE_TITLE = "expense_title"
        const val EXPENSE_TIME = "time"
        const val INCOME_TITLE = "income_title"
        const val INCOME_TIME = "time"


        const val INCOME_EXPENSE_SITE_ID = "site_id"
        const val INCOME_EXPENSE_SITE_NAME = "site_name"
        const val INCOME_EXPENSE_CATEGORY_ID = "category_id"
        const val INCOME_EXPENSE_CATEGORY_NAME = "category_name"
        const val INCOME_EXPENSE_TIME = "time"
        const val INCOME_EXPENSE_PAYMENT = "payment"
        const val INCOME_EXPENSE_REASON = "reason"
        const val INCOME_EXPENSE_TYPE = "type"






    }
}